#ifndef KUGOU_API_H
#define KUGOU_API_H

#include <stdio.h>
#include <stdlib.h>

typedef struct KugouProcessEnv {
  char *platform;
  char *KUGOU_API_GUID;
  char *KUGOU_API_DEV;
  char *KUGOU_API_MAC;
} KugouProcessEnv;
typedef struct JSContext JSContext;
JSContext *kugou_init(KugouProcessEnv *env);
JSContext *kugou_init_simple();
int kugou_destroy();
JSContext *get_kugou_context();

char *kugou_request(JSContext *ctx, const char *route, const char *cookies, const char *params, KugouProcessEnv *env);
char *kugou_request_simple(JSContext *ctx, const char *route, const char *cookies, const char *params);
typedef struct KugouAPI
{
  char *(*yueku_fm)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*yueku_fm_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*yueku_banner)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*yueku_banner_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*yueku)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*yueku_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*youth_vip)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*youth_vip_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*youth_user_song)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*youth_user_song_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*youth_union_vip)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*youth_union_vip_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*youth_month_vip_record)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*youth_month_vip_record_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*youth_listen_song)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*youth_listen_song_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*youth_dynamic_recent)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*youth_dynamic_recent_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*youth_dynamic)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*youth_dynamic_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*youth_day_vip_upgrade)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*youth_day_vip_upgrade_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*youth_day_vip)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*youth_day_vip_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*youth_channel_sub)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*youth_channel_sub_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*youth_channel_song_detail)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*youth_channel_song_detail_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*youth_channel_song)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*youth_channel_song_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*youth_channel_similar)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*youth_channel_similar_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*youth_channel_detail)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*youth_channel_detail_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*youth_channel_amway)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*youth_channel_amway_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*youth_channel_all)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*youth_channel_all_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*video_url)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*video_url_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*video_privilege)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*video_privilege_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*video_detail)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*video_detail_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*user_vip_detail)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*user_vip_detail_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*user_video_love)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*user_video_love_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*user_video_collect)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*user_video_collect_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*user_playlist)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*user_playlist_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*user_listen)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*user_listen_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*user_history)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*user_history_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*user_follow)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*user_follow_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*user_detail)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*user_detail_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*user_cloud_url)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*user_cloud_url_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*user_cloud)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*user_cloud_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*top_song)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*top_song_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*top_playlist)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*top_playlist_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*top_ip)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*top_ip_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*top_card_youth)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*top_card_youth_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*top_card)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*top_card_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*top_album)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*top_album_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*theme_playlist_track)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*theme_playlist_track_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*theme_playlist)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*theme_playlist_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*theme_music_detail)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*theme_music_detail_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*theme_music)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*theme_music_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*song_url_new)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*song_url_new_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*song_url)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*song_url_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*song_ranking_filter)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*song_ranking_filter_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*song_ranking)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*song_ranking_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*song_climax)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*song_climax_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*singer_list)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*singer_list_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*sheet_list)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*sheet_list_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*sheet_hot)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*sheet_hot_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*sheet_detail)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*sheet_detail_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*sheet_collection_detail)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*sheet_collection_detail_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*sheet_collection)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*sheet_collection_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*server_now)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*server_now_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*search_suggest)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*search_suggest_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*search_mixed)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*search_mixed_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*search_lyric)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*search_lyric_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*search_hot)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*search_hot_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*search_default)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*search_default_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*search_complex)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*search_complex_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*search)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*search_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*scene_video_list)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*scene_video_list_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*scene_music)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*scene_music_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*scene_module_info)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*scene_module_info_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*scene_module)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*scene_module_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*scene_lists_v2)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*scene_lists_v2_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*scene_lists)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*scene_lists_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*scene_collection_list)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*scene_collection_list_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*scene_audio_list)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*scene_audio_list_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*register_dev)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*register_dev_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*recommend_songs)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*recommend_songs_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*rank_vol)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*rank_vol_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*rank_top)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*rank_top_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*rank_list)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*rank_list_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*rank_info)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*rank_info_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*rank_audio)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*rank_audio_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*privilege_lite)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*privilege_lite_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*playlist_tracks_del)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*playlist_tracks_del_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*playlist_tracks_add)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*playlist_tracks_add_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*playlist_track_all_new)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*playlist_track_all_new_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*playlist_track_all)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*playlist_track_all_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*playlist_tags)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*playlist_tags_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*playlist_similar)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*playlist_similar_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*playlist_effect)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*playlist_effect_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*playlist_detail)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*playlist_detail_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*playlist_del)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*playlist_del_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*playlist_add)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*playlist_add_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*playhistory_upload)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*playhistory_upload_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*personal_fm)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*personal_fm_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*pc_diantai)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*pc_diantai_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*lyric)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*lyric_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*longaudio_week_recommend)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*longaudio_week_recommend_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*longaudio_vip_recommend)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*longaudio_vip_recommend_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*longaudio_rank_recommend)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*longaudio_rank_recommend_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*longaudio_daily_recommend)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*longaudio_daily_recommend_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*longaudio_album_detail)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*longaudio_album_detail_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*longaudio_album_audios)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*longaudio_album_audios_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*login_wx_create)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*login_wx_create_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*login_wx_check)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*login_wx_check_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*login_token)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*login_token_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*login_qr_key)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*login_qr_key_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*login_qr_create)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*login_qr_create_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*login_qr_check)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*login_qr_check_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*login_openplat)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*login_openplat_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*login_device)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*login_device_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*login_cellphone)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*login_cellphone_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*login)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*login_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*lastest_songs_listen)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*lastest_songs_listen_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*krm_audio)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*krm_audio_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*kmr_audio_mv)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*kmr_audio_mv_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*ip_zone_home)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*ip_zone_home_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*ip_zone)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*ip_zone_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*ip_playlist)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*ip_playlist_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*ip_dateil)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*ip_dateil_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*ip)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*ip_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*images_audio)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*images_audio_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*images)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*images_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*fm_songs)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*fm_songs_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*fm_recommend)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*fm_recommend_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*fm_image)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*fm_image_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*fm_class)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*fm_class_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*favorite_count)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*favorite_count_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*everyday_style_recommend)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*everyday_style_recommend_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*everyday_recommend)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*everyday_recommend_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*everyday_history)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*everyday_history_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*everyday_friend)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*everyday_friend_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*comment_playlist)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*comment_playlist_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*comment_music_hotword)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*comment_music_hotword_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*comment_music_classify)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*comment_music_classify_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*comment_music)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*comment_music_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*comment_floor)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*comment_floor_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*comment_count)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*comment_count_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*comment_album)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*comment_album_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*captcha_sent)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*captcha_sent_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*brush)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*brush_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*audio_related)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*audio_related_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*audio_ktv_total)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*audio_ktv_total_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*audio_accompany_matching)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*audio_accompany_matching_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*audio)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*audio_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*artist_videos)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*artist_videos_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*artist_unfollow)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*artist_unfollow_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*artist_lists)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*artist_lists_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*artist_honour)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*artist_honour_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*artist_follow_newsongs)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*artist_follow_newsongs_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*artist_follow)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*artist_follow_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*artist_detail)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*artist_detail_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*artist_audios)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*artist_audios_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*artist_albums)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*artist_albums_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*album_songs)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*album_songs_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*album_shop)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*album_shop_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*album_detail)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*album_detail_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*album)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*album_simple)(JSContext *ctx, const char *cookies, const char *params);
  char *(*ai_recommend)(JSContext *ctx, const char *cookies, const char *params, KugouProcessEnv *env);
  char *(*ai_recommend_simple)(JSContext *ctx, const char *cookies, const char *params);
} KugouAPI;

KugouAPI *create_kugou_api();

#endif